In [16]:
import pandas as pd
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

# Load your dataset with encoding set to latin1
df = pd.read_csv('globe_all_countries_jobs_data.csv', encoding='latin1')
df.head()
# Clean up column names by stripping leading and trailing spaces
df.columns = df.columns.str.strip()

# Initialize Dash app
app = dash.Dash(__name__)

# Extract unique countries from the dataset
countries = df['Country Name'].dropna().unique()
selected_aspects = [
    'Access to electricity (% of population)',
    'Employment in services (% of total employment) (modeled ILO estimate)',
#     'Agriculture value added (% of GDP)',
#     'Unemployment with advanced education (% of total labor force with advanced education)',
#     'Life expectancy at birth total (years)'
]

# Define app layout
app.layout = html.Div([
    html.H1("Country Evaluation Dashboard"),
    dcc.Dropdown(id='country-dropdown', options=[{'label': country, 'value': country} for country in countries], value=countries[0], style={'width': '50%'}),
    dcc.Dropdown(id='aspect-dropdown', options=[{'label': aspect, 'value': aspect} for aspect in selected_aspects], value=selected_aspects[0], style={'width': '50%'}),
    dcc.Graph(id='aspect-comparison-chart')
])

# Define callback to update graph based on selected country and aspect
@app.callback(
    Output('aspect-comparison-chart', 'figure'),
    [Input('country-dropdown', 'value'),
     Input('aspect-dropdown', 'value')]
)
def update_comparison_chart(selected_country, selected_aspect):
    # Filter dataset based on selected country and aspect
    filtered_data = df[(df['Country Name'] == selected_country) & (df['Series Name'] == selected_aspect)]

    # Extract years and corresponding values for the selected aspect (from '1995 [YR1995]' to '2016 [YR2016]')
    years = [f"{year} [YR{year}]" for year in range(1995, 2017)]
    values = filtered_data[years].values.tolist()[0]  # Assuming only one row matches

    # Create line plot for the selected aspect
    fig = px.line(x=years, y=values, labels={'x': 'Year', 'y': selected_aspect}, title=f'{selected_aspect} in {selected_country} (1995 to 2016)', markers=True)
     
    return fig

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8051)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[16], line 49, in update_comparison_chart(selected_country='Afghanistan')
     46 values = filtered_data[years].values.tolist()[0]  # Assuming only one row matches
     48 # Create line plot for the selected aspect
---> 49 fig = px.line(x=years, y=values, labels={'x': 'Year', 'y': selected_aspect}, title=f'{selected_aspect} in {selected_country} (1995 to 2016)', markers=True)
        years = ['1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]']
        values = ['0.00999999977648258', '0.00999999977648258', '0.00999999977648258', '0.0219771377742291', '0.179634585976601', '0.959755897521973', '0.77653694152832', '6.26739358901977', '11.7519664764404', '17.2363185882568', '23', '28.2286128997803', '33.7486801147461', '42.4', '44.8548851013184', '42.7', '43.2220189082037', '69.1', '67.2595520019531', '89.5', '71.5', '84.1371383666992']
        selected_country = 'Afghanistan'
        px = <module 'plotly.express' from 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python311\\site-packages\\plotly\\express\\__init__.py'>
     51 return fig

NameError: name 'selected_aspect' is not defined

In [13]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd

# Sample data
companies = ['Company A', 'Company B', 'Company C']
# Assuming you have a DataFrame named 'data' with columns 'Company' and 'Job Title'
data = pd.read_csv('linkedin_job_postings.csv')
app = dash.Dash(__name__)

app.layout = html.Div([
    html.H3('Choose Company'),
    dcc.Dropdown(
        id='company-dropdown',
        options=[{'label': company, 'value': company} for company in companies],
        value='Company A'
    ),
    dcc.Graph(id='company-comparison-chart')
])

@app.callback(
    Output('company-comparison-chart', 'figure'),
    [Input('company-dropdown', 'value')]
)
def update_chart(selected_company):
    # Filter data for the selected company
    company_data = data[data['Company'] == selected_company]
    # Count occurrences of each job title
    job_counts = company_data['Job Title'].value_counts()
    # Create a bar plot
    fig = px.bar(x=job_counts.index, y=job_counts.values, labels={'x': 'Job Title', 'y': 'Count'})
    fig.update_layout(title=f'Job Titles Distribution for {selected_company}')
    return fig

if __name__ == '__main__':
    app.run_server(debug=True, port = 7050)

In [14]:
import pandas as pd
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

# Load your dataset with encoding set to latin1
df = pd.read_csv('globe_all_countries_jobs_data.csv', encoding='latin1')
df.head()

,Country Name,Country Code,Series Name,Series Code,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],...,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016]
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.00999999977648258,0.00999999977648258,0.00999999977648258,0.00999999977648258,0.00999999977648258,0.00999999977648258,...,33.7486801147461,42.4,44.8548851013184,42.7,43.2220189082037,69.1,67.2595520019531,89.5,71.5,84.1371383666992
1,Afghanistan,AFG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,162.8354,163.3822,163.929,164.1888,164.4486,164.7084,...,117.396,111.1414,104.8868,98.6322,92.3776,86.123,81.7908,77.4586,73.1264,68.7942
2,Afghanistan,AFG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,101.018259850238,100.96564733016,100.870231727519,100.902317661547,100.887270633256,100.510118469483,...,100.231023134586,100.656496083108,100.740812582094,100.406411520766,98.7307589652135,96.5285898367748,94.0017341230592,91.3762048564238,88.7687273393836,86.5709321507136
3,Afghanistan,AFG,"Agriculture, value added (% of GDP)",NV.AGR.TOTL.ZS,..,..,..,..,..,..,...,29.7989655280121,24.6938230129889,29.1359284351699,26.0782527819623,23.5779686892153,23.6436386470918,22.587453161034,22.009298022763,20.5469658803948,20.9658976104561
4,Afghanistan,AFG,"Agriculture, value added (annual % growth)",NV.AGR.TOTL.KD.ZG,..,..,..,..,..,..,...,14.6947633410373,-14.9167175639132,44.5654473278869,-6.37380492600464,-7.59086467916443,18.2247894194574,0.00517080272992132,-0.100457250332653,-5.65736076451711,5.97175068925613

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[5], line 47, in update_comparison_chart(
    selected_country=None,
    selected_aspect='Access to electricity (% of population)'
)
     45 # Extract years and corresponding values for the selected aspect (from '1995 [YR1995]' to '2016 [YR2016]')
     46 years = [f"{year} [YR{year}]" for year in range(1995, 2017)]
---> 47 values = filtered_data[years].values.tolist()[0]  # Assuming only one row matches
        filtered_data = Empty DataFrame
Columns: [Country Name, Country Code, Series Name, Series Code, 1990 [YR1990], 1991 [YR1991], 1992 [YR1992], 1993 [YR1993], 1994 [YR1994], 1995 [YR1995], 1996 [YR1996], 1997 [YR1997], 1998 [YR1998], 1999 [YR1999], 2000 [YR2000], 2001 [YR2001], 2002 [YR2002], 2003 [YR2003], 2004 [YR2004], 2005 [YR2005], 2006 [YR2006], 2007 [YR2007], 2008 [YR2008], 2009 [YR2009], 2010 [YR2010], 2011 [YR2011], 2012 [YR2012], 2013 [YR2013], 2014 [YR2014], 2015 [YR2015], 2016 [YR2016]]
Index: []

[0 rows x 31 columns]
        years = ['1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]']
     49 # Create line plot for the selected aspect
     50 fig = px.line(x=years, y=values, labels={'x': 'Year', 'y': selected_aspect}, title=f'{selected_aspect} in {selected_country} (1995 to 2016)', markers=True)

IndexError: list index out of range

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[5], line 47, in update_comparison_chart(
    selected_country=None,
    selected_aspect='Access to electricity (% of population)'
)
     45 # Extract years and corresponding values for the selected aspect (from '1995 [YR1995]' to '2016 [YR2016]')
     46 years = [f"{year} [YR{year}]" for year in range(1995, 2017)]
---> 47 values = filtered_data[years].values.tolist()[0]  # Assuming only one row matches
        filtered_data = Empty DataFrame
Columns: [Country Name, Country Code, Series Name, Series Code, 1990 [YR1990], 1991 [YR1991], 1992 [YR1992], 1993 [YR1993], 1994 [YR1994], 1995 [YR1995], 1996 [YR1996], 1997 [YR1997], 1998 [YR1998], 1999 [YR1999], 2000 [YR2000], 2001 [YR2001], 2002 [YR2002], 2003 [YR2003], 2004 [YR2004], 2005 [YR2005], 2006 [YR2006], 2007 [YR2007], 2008 [YR2008], 2009 [YR2009], 2010 [YR2010], 2011 [YR2011], 2012 [YR2012], 2013 [YR2013], 2014 [YR2014], 2015 [YR2015], 2016 [YR2016]]
Index: []

[0 rows x 31 columns]
        years = ['1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]']
     49 # Create line plot for the selected aspect
     50 fig = px.line(x=years, y=values, labels={'x': 'Year', 'y': selected_aspect}, title=f'{selected_aspect} in {selected_country} (1995 to 2016)', markers=True)

IndexError: list index out of range